//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/dsl/Column.java
//

#ifndef _Column_H_
#define _Column_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaColumn < JavaLangAnnotationAnnotation >

@property (readonly) NSString *name;
@property (readonly) jboolean unique;
@property (readonly) jboolean notNull;

@end

@interface JavaColumn : NSObject < JavaColumn > {
 @private
  NSString *name_;
  jboolean unique_;
  jboolean notNull_;
}

- (instancetype)initWithName:(NSString *)name__ withNotNull:(jboolean)notNull__ withUnique:(jboolean)unique__;

+ (jboolean)uniqueDefault;
+ (jboolean)notNullDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaColumn)

J2OBJC_TYPE_LITERAL_HEADER(JavaColumn)

#define NetSkoumalJoogarSharedDslColumn JavaColumn

#endif // _Column_H_
