//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/dsl/Column.java
//

#include "Column.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"

@implementation JavaColumn

@synthesize name = name_;
@synthesize unique = unique_;
@synthesize notNull = notNull_;

- (instancetype)initWithName:(NSString *)name__ withNotNull:(jboolean)notNull__ withUnique:(jboolean)unique__ {
  if ((self = [super init])) {
    self->name_ = RETAIN_(name__);
    self->notNull_ = notNull__;
    self->unique_ = unique__;
  }
  return self;
}

+ (jboolean)uniqueDefault {
  return false;
}

+ (jboolean)notNullDefault {
  return false;
}

- (IOSClass *)annotationType {
  return JavaColumn_class_();
}

- (NSString *)description {
  return @"@net.skoumal.joogar.shared.dsl.Column()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "name", "name", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "nameDefault", "name", "Ljava.lang.String;", 0x100a, NULL, NULL },
    { "unique", "unique", "Z", 0x401, NULL, NULL },
    { "uniqueDefault", "unique", "Z", 0x100a, NULL, NULL },
    { "notNull", "notNull", "Z", 0x401, NULL, NULL },
    { "notNullDefault", "notNull", "Z", 0x100a, NULL, NULL },
  };
  static const J2ObjcClassInfo _JavaColumn = { 2, "Column", "net.skoumal.joogar.shared.dsl", NULL, 0x2609, 6, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaColumn;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaColumn)
