//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/dsl/Ignore.java
//

#include "IOSClass.h"
#include "Ignore.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"

@implementation JavaIgnore

- (IOSClass *)annotationType {
  return JavaIgnore_class_();
}

- (NSString *)description {
  return @"@net.skoumal.joogar.shared.dsl.Ignore()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _JavaIgnore = { 2, "Ignore", "net.skoumal.joogar.shared.dsl", NULL, 0x2609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaIgnore;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaIgnore)
