//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/dsl/Ignore.java
//

#ifndef _Ignore_H_
#define _Ignore_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaIgnore < JavaLangAnnotationAnnotation >

@end

@interface JavaIgnore : NSObject < JavaIgnore >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaIgnore)

J2OBJC_TYPE_LITERAL_HEADER(JavaIgnore)

#define NetSkoumalJoogarSharedDslIgnore JavaIgnore

#endif // _Ignore_H_
