//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/cursor/JoogarCursorList.java
//

#ifndef _JoogarCursorList_H_
#define _JoogarCursorList_H_

#include "J2ObjC_header.h"
#include "JoogarCursor.h"

@class IOSClass;
@protocol JavaUtilIterator;
@protocol JavaUtilList;

@interface JavaJoogarCursorList : NSObject < JavaJoogarCursor >

#pragma mark Public

- (instancetype)initWithIOSClass:(IOSClass *)gType
                withJavaUtilList:(id<JavaUtilList>)gList;

- (void)close;

- (id)current;

- (jint)getCount;

- (id)getItem;

- (jint)getPosition;

- (jboolean)hasNext;

- (jboolean)isClosed;

- (id<JavaUtilIterator>)iterator;

- (id)next;

- (void)setPositionWithInt:(jint)gPosition;

- (jint)size;

- (id<JavaUtilList>)toList;

- (id<JavaUtilList>)toListAndClose;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogarCursorList)

FOUNDATION_EXPORT void JavaJoogarCursorList_initWithIOSClass_withJavaUtilList_(JavaJoogarCursorList *self, IOSClass *gType, id<JavaUtilList> gList);

FOUNDATION_EXPORT JavaJoogarCursorList *new_JavaJoogarCursorList_initWithIOSClass_withJavaUtilList_(IOSClass *gType, id<JavaUtilList> gList) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogarCursorList)

@compatibility_alias NetSkoumalJoogarSharedCursorJoogarCursorList JavaJoogarCursorList;

#endif // _JoogarCursorList_H_
