//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/Joogar.java
//

#ifndef _Joogar_H_
#define _Joogar_H_

#include "J2ObjC_header.h"

@class IOSClass;
@class JavaJoogarDatabase;
@class JavaJoogarDatabaseBuilder;
@class JavaReflectionUtils;
@protocol JavaJoogarLogger;
@protocol JavaSystemUtils;
@protocol JavaUtilList;

@interface JavaJoogar : NSObject

#pragma mark Public

- (JavaJoogar *)addDBWithJavaJoogarDatabaseBuilder:(JavaJoogarDatabaseBuilder *)gBuilder;

- (void)close;

- (JavaJoogarDatabase *)getDB;

- (JavaJoogarDatabase *)getDBWithIOSClass:(IOSClass *)gType;

- (JavaJoogarDatabase *)getDBWithNSString:(NSString *)dbName;

- (id<JavaUtilList>)getDBList;

+ (JavaJoogar *)getInstance;

- (id<JavaJoogarLogger>)getLogger;

- (JavaReflectionUtils *)getReflectionUtils;

- (id<JavaSystemUtils>)getSystemUtils;

+ (JavaJoogar *)initForAndroidWithId:(id)gContext OBJC_METHOD_FAMILY_NONE;

+ (JavaJoogar *)initForIos OBJC_METHOD_FAMILY_NONE;

+ (jboolean)isDebug;

+ (void)setDebugWithBoolean:(jboolean)gDebug;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogar)

FOUNDATION_EXPORT JavaJoogar *JavaJoogar_getInstance();

FOUNDATION_EXPORT JavaJoogar *JavaJoogar_initForAndroidWithId_(id gContext);

FOUNDATION_EXPORT JavaJoogar *JavaJoogar_initForIos();

FOUNDATION_EXPORT jboolean JavaJoogar_isDebug();

FOUNDATION_EXPORT void JavaJoogar_setDebugWithBoolean_(jboolean gDebug);

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogar)

@compatibility_alias NetSkoumalJoogarSharedJoogar JavaJoogar;

#endif // _Joogar_H_
