//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/JoogarDatabaseResult.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "JoogarDatabaseResult.h"

@interface JavaJoogarDatabaseResult : NSObject

@end

@implementation JavaJoogarDatabaseResult

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "Z", 0x401, NULL, NULL },
    { "close", NULL, "V", 0x401, NULL, NULL },
    { "count", NULL, "I", 0x401, NULL, NULL },
    { "getPosition", NULL, "I", 0x401, NULL, NULL },
    { "getColumnIndexWithNSString:", "getColumnIndex", "I", 0x401, NULL, NULL },
    { "isNullWithInt:", "isNull", "Z", 0x401, NULL, NULL },
    { "getLongWithInt:", "getLong", "J", 0x401, NULL, NULL },
    { "getStringWithInt:", "getString", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getDoubleWithInt:", "getDouble", "D", 0x401, NULL, NULL },
    { "getBlobWithInt:", "getBlob", "[B", 0x401, NULL, NULL },
    { "getIntWithInt:", "getInt", "I", 0x401, NULL, NULL },
    { "getFloatWithInt:", "getFloat", "F", 0x401, NULL, NULL },
    { "setPositionWithInt:", "setPosition", "V", 0x401, NULL, NULL },
    { "allowsRandomAccess", NULL, "Z", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _JavaJoogarDatabaseResult = { 2, "JoogarDatabaseResult", "net.skoumal.joogar.shared", NULL, 0x609, 14, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaJoogarDatabaseResult;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaJoogarDatabaseResult)
