//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/JoogarLogger.java
//

#ifndef _JoogarLogger_H_
#define _JoogarLogger_H_

#include "J2ObjC_header.h"

@protocol JavaJoogarLogger < NSObject, JavaObject >

- (void)eWithNSString:(NSString *)gMsg;

- (void)wWithNSString:(NSString *)gMsg;

- (void)iWithNSString:(NSString *)gMsg;

- (void)dWithNSString:(NSString *)gMsg;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogarLogger)

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogarLogger)

#define NetSkoumalJoogarSharedJoogarLogger JavaJoogarLogger

#endif // _JoogarLogger_H_
