//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/JoogarObjectAbstractFactory.java
//

#include "J2ObjC_source.h"
#include "JoogarDatabase.h"
#include "JoogarLogger.h"
#include "JoogarObjectAbstractFactory.h"
#include "ReflectionUtils.h"
#include "SystemUtils.h"
#include "java/io/File.h"

@interface JavaJoogarObjectAbstractFactory : NSObject

@end

@implementation JavaJoogarObjectAbstractFactory

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getLogger", NULL, "Lnet.skoumal.joogar.shared.JoogarLogger;", 0x401, NULL, NULL },
    { "getDatabaseWithNSString:", "getDatabase", "Lnet.skoumal.joogar.shared.JoogarDatabase;", 0x401, NULL, NULL },
    { "getDatabaseWithJavaIoFile:", "getDatabase", "Lnet.skoumal.joogar.shared.JoogarDatabase;", 0x401, NULL, NULL },
    { "getSystemUtils", NULL, "Lnet.skoumal.joogar.shared.SystemUtils;", 0x401, NULL, NULL },
    { "getReflectionUtils", NULL, "Lnet.skoumal.joogar.shared.util.ReflectionUtils;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _JavaJoogarObjectAbstractFactory = { 2, "JoogarObjectAbstractFactory", "net.skoumal.joogar.shared", NULL, 0x609, 5, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaJoogarObjectAbstractFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaJoogarObjectAbstractFactory)
