//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/cursor/JoogarCursor.java
//

#ifndef _JoogarCursor_H_
#define _JoogarCursor_H_

#include "J2ObjC_header.h"
#include "java/lang/Iterable.h"

@protocol JavaUtilList;

@protocol JavaJoogarCursor < JavaLangIterable, NSObject, JavaObject >

- (jint)getCount;

- (jint)size;

- (jint)getPosition;

- (void)setPositionWithInt:(jint)position;

- (id)next;

- (jboolean)hasNext;

- (void)close;

- (jboolean)isClosed;

- (id)getItem;

- (id)current;

- (id<JavaUtilList>)toList;

- (id<JavaUtilList>)toListAndClose;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogarCursor)

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogarCursor)

#define NetSkoumalJoogarSharedCursorJoogarCursor JavaJoogarCursor

#endif // _JoogarCursor_H_
