//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/JoogarDatabaseResult.java
//

#ifndef _JoogarDatabaseResult_H_
#define _JoogarDatabaseResult_H_

#include "J2ObjC_header.h"

@class IOSByteArray;

@protocol JavaJoogarDatabaseResult < NSObject, JavaObject >

- (jboolean)next;

- (void)close;

- (jint)count;

- (jint)getPosition;

- (jint)getColumnIndexWithNSString:(NSString *)colName;

- (jboolean)isNullWithInt:(jint)columnIndex;

- (jlong)getLongWithInt:(jint)columnIndex;

- (NSString *)getStringWithInt:(jint)columnIndex;

- (jdouble)getDoubleWithInt:(jint)columnIndex;

- (IOSByteArray *)getBlobWithInt:(jint)columnIndex;

- (jint)getIntWithInt:(jint)columnIndex;

- (jfloat)getFloatWithInt:(jint)columnIndex;

- (void)setPositionWithInt:(jint)position;

- (jboolean)allowsRandomAccess;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogarDatabaseResult)

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogarDatabaseResult)

#define NetSkoumalJoogarSharedJoogarDatabaseResult JavaJoogarDatabaseResult

#endif // _JoogarDatabaseResult_H_
