//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/util/JoogarUpgradeScriptComparator.java
//

#ifndef _JoogarUpgradeScriptComparator_H_
#define _JoogarUpgradeScriptComparator_H_

#include "J2ObjC_header.h"
#include "java/util/Comparator.h"

@interface JavaJoogarUpgradeScriptComparator : NSObject < JavaUtilComparator >

#pragma mark Public

- (instancetype)init;

- (jint)compareWithId:(id)o1
               withId:(id)o2;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogarUpgradeScriptComparator)

FOUNDATION_EXPORT void JavaJoogarUpgradeScriptComparator_init(JavaJoogarUpgradeScriptComparator *self);

FOUNDATION_EXPORT JavaJoogarUpgradeScriptComparator *new_JavaJoogarUpgradeScriptComparator_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogarUpgradeScriptComparator)

@compatibility_alias NetSkoumalJoogarSharedUtilJoogarUpgradeScriptComparator JavaJoogarUpgradeScriptComparator;

#endif // _JoogarUpgradeScriptComparator_H_
