//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/cursor/JoogarCursor.java
//

#include "J2ObjC_source.h"
#include "JoogarCursor.h"
#include "java/util/List.h"

@interface JavaJoogarCursor : NSObject

@end

@implementation JavaJoogarCursor

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getCount", NULL, "I", 0x401, NULL, NULL },
    { "size", NULL, "I", 0x401, NULL, NULL },
    { "getPosition", NULL, "I", 0x401, NULL, NULL },
    { "setPositionWithInt:", "setPosition", "V", 0x401, NULL, NULL },
    { "next", NULL, "TT;", 0x401, NULL, "()TT;" },
    { "hasNext", NULL, "Z", 0x401, NULL, NULL },
    { "close", NULL, "V", 0x401, NULL, NULL },
    { "isClosed", NULL, "Z", 0x401, NULL, NULL },
    { "getItem", NULL, "TT;", 0x401, NULL, "()TT;" },
    { "current", NULL, "TT;", 0x401, NULL, "()TT;" },
    { "toList", NULL, "Ljava.util.List;", 0x401, NULL, NULL },
    { "toListAndClose", NULL, "Ljava.util.List;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _JavaJoogarCursor = { 2, "JoogarCursor", "net.skoumal.joogar.shared.cursor", NULL, 0x609, 12, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;Ljava/lang/Iterable<TT;>;" };
  return &_JavaJoogarCursor;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaJoogarCursor)
