//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/util/JoogarConfig.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "JoogarConfig.h"
#include "java/util/Collections.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

J2OBJC_INITIALIZED_DEFN(JavaJoogarConfig)

id<JavaUtilMap> JavaJoogarConfig_fields_;

@implementation JavaJoogarConfig

+ (void)setFieldsWithIOSClass:(IOSClass *)clazz
             withJavaUtilList:(id<JavaUtilList>)fieldz {
  JavaJoogarConfig_setFieldsWithIOSClass_withJavaUtilList_(clazz, fieldz);
}

+ (id<JavaUtilList>)getFieldsWithIOSClass:(IOSClass *)clazz {
  return JavaJoogarConfig_getFieldsWithIOSClass_(clazz);
}

+ (void)clearCache {
  JavaJoogarConfig_clearCache();
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  JavaJoogarConfig_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initialize {
  if (self == [JavaJoogarConfig class]) {
    JavaJoogarConfig_fields_ = new_JavaUtilHashMap_init();
    J2OBJC_SET_INITIALIZED(JavaJoogarConfig)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setFieldsWithIOSClass:withJavaUtilList:", "setFields", "V", 0x9, NULL, NULL },
    { "getFieldsWithIOSClass:", "getFields", "Ljava.util.List;", 0x9, NULL, NULL },
    { "clearCache", NULL, "V", 0x9, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "fields_", NULL, 0x8, "Ljava.util.Map;", &JavaJoogarConfig_fields_, "Ljava/util/Map<Ljava/lang/Class<*>;Ljava/util/List<Ljava/lang/reflect/Field;>;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _JavaJoogarConfig = { 2, "JoogarConfig", "net.skoumal.joogar.shared.util", NULL, 0x1, 4, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaJoogarConfig;
}

@end

void JavaJoogarConfig_setFieldsWithIOSClass_withJavaUtilList_(IOSClass *clazz, id<JavaUtilList> fieldz) {
  JavaJoogarConfig_initialize();
  (void) [((id<JavaUtilMap>) nil_chk(JavaJoogarConfig_fields_)) putWithId:clazz withId:fieldz];
}

id<JavaUtilList> JavaJoogarConfig_getFieldsWithIOSClass_(IOSClass *clazz) {
  JavaJoogarConfig_initialize();
  if ([((id<JavaUtilMap>) nil_chk(JavaJoogarConfig_fields_)) containsKeyWithId:clazz]) {
    id<JavaUtilList> list = [JavaJoogarConfig_fields_ getWithId:clazz];
    return JavaUtilCollections_synchronizedListWithJavaUtilList_(list);
  }
  return nil;
}

void JavaJoogarConfig_clearCache() {
  JavaJoogarConfig_initialize();
  [((id<JavaUtilMap>) nil_chk(JavaJoogarConfig_fields_)) clear];
  JavaJoogarConfig_fields_ = new_JavaUtilHashMap_init();
}

void JavaJoogarConfig_init(JavaJoogarConfig *self) {
  (void) NSObject_init(self);
}

JavaJoogarConfig *new_JavaJoogarConfig_init() {
  JavaJoogarConfig *self = [JavaJoogarConfig alloc];
  JavaJoogarConfig_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(JavaJoogarConfig)
