//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/JoogarDatabaseBuilder.java
//

#ifndef _JoogarDatabaseBuilder_H_
#define _JoogarDatabaseBuilder_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class JavaIoFile;
@class JavaJoogarDatabase;
@protocol JavaJoogarObjectAbstractFactory;
@protocol JavaUtilList;

@interface JavaJoogarDatabaseBuilder : NSObject

#pragma mark Public

- (instancetype)init;

- (JavaJoogarDatabase *)buildWithJavaJoogarObjectAbstractFactory:(id<JavaJoogarObjectAbstractFactory>)gObjectFactory;

- (id<JavaUtilList>)getDomainClasses;

- (NSString *)getName;

- (JavaJoogarDatabaseBuilder *)setDomainClassesWithIOSClassArray:(IOSObjectArray *)domainClasses;

- (JavaJoogarDatabaseBuilder *)setDomainClassesWithJavaUtilList:(id<JavaUtilList>)domainClasses;

- (JavaJoogarDatabaseBuilder *)setFileWithJavaIoFile:(JavaIoFile *)path;

- (JavaJoogarDatabaseBuilder *)setNameWithNSString:(NSString *)name;

- (JavaJoogarDatabaseBuilder *)setVersionWithInt:(jint)version_;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogarDatabaseBuilder)

FOUNDATION_EXPORT void JavaJoogarDatabaseBuilder_init(JavaJoogarDatabaseBuilder *self);

FOUNDATION_EXPORT JavaJoogarDatabaseBuilder *new_JavaJoogarDatabaseBuilder_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogarDatabaseBuilder)

@compatibility_alias NetSkoumalJoogarSharedJoogarDatabaseBuilder JavaJoogarDatabaseBuilder;

#endif // _JoogarDatabaseBuilder_H_
