//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/JoogarLogger.java
//

#include "J2ObjC_source.h"
#include "JoogarLogger.h"

@interface JavaJoogarLogger : NSObject

@end

@implementation JavaJoogarLogger

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "eWithNSString:", "e", "V", 0x401, NULL, NULL },
    { "wWithNSString:", "w", "V", 0x401, NULL, NULL },
    { "iWithNSString:", "i", "V", 0x401, NULL, NULL },
    { "dWithNSString:", "d", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _JavaJoogarLogger = { 2, "JoogarLogger", "net.skoumal.joogar.shared", NULL, 0x609, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaJoogarLogger;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaJoogarLogger)
