//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/JoogarDatabase.java
//

#ifndef _JoogarDatabase_H_
#define _JoogarDatabase_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class JavaIoFile;
@protocol JavaJoogarDatabaseResult;
@protocol JavaUtilList;

@interface JavaJoogarDatabase : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaIoFile:(JavaIoFile *)gPath;

- (void)close;

- (void)commitTransaction;

- (jint)delete__WithNSString:(NSString *)table
                withNSString:(NSString *)whereClause
           withNSStringArray:(IOSObjectArray *)whereArgs;

- (jint)execSQLWithNSString:(NSString *)query
          withNSStringArray:(IOSObjectArray *)arguments;

- (JavaIoFile *)getPath;

- (jint)getVersion;

- (jlong)insertOrUpdateWithNSString:(NSString *)table
                   withJavaUtilList:(id<JavaUtilList>)columns
                  withNSObjectArray:(IOSObjectArray *)values;

- (void)openTransaction;

- (id<JavaJoogarDatabaseResult>)queryWithNSString:(NSString *)table
                                     withNSString:(NSString *)join
                                withNSStringArray:(IOSObjectArray *)columns
                                     withNSString:(NSString *)whereClause
                                withNSStringArray:(IOSObjectArray *)whereArgs
                                     withNSString:(NSString *)groupBy
                                     withNSString:(NSString *)having
                                     withNSString:(NSString *)orderBy
                                     withNSString:(NSString *)limit;

- (id<JavaJoogarDatabaseResult>)rawQueryWithNSString:(NSString *)query
                                   withNSStringArray:(IOSObjectArray *)arguments;

- (void)rollbackTransaction;

- (void)setVersionWithInt:(jint)gVersion;

#pragma mark Protected

- (jlong)insertOrUpdateInternalWithNSString:(NSString *)gSqlStr
                          withNSObjectArray:(IOSObjectArray *)gValue;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogarDatabase)

FOUNDATION_EXPORT void JavaJoogarDatabase_initWithJavaIoFile_(JavaJoogarDatabase *self, JavaIoFile *gPath);

FOUNDATION_EXPORT void JavaJoogarDatabase_init(JavaJoogarDatabase *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogarDatabase)

@compatibility_alias NetSkoumalJoogarSharedJoogarDatabase JavaJoogarDatabase;

#endif // _JoogarDatabase_H_
