//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/JoogarObjectAbstractFactory.java
//

#ifndef _JoogarObjectAbstractFactory_H_
#define _JoogarObjectAbstractFactory_H_

#include "J2ObjC_header.h"

@class JavaIoFile;
@class JavaJoogarDatabase;
@class JavaReflectionUtils;
@protocol JavaJoogarLogger;
@protocol JavaSystemUtils;

@protocol JavaJoogarObjectAbstractFactory < NSObject, JavaObject >

- (id<JavaJoogarLogger>)getLogger;

- (JavaJoogarDatabase *)getDatabaseWithNSString:(NSString *)gName;

- (JavaJoogarDatabase *)getDatabaseWithJavaIoFile:(JavaIoFile *)gPath;

- (id<JavaSystemUtils>)getSystemUtils;

- (JavaReflectionUtils *)getReflectionUtils;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaJoogarObjectAbstractFactory)

J2OBJC_TYPE_LITERAL_HEADER(JavaJoogarObjectAbstractFactory)

#define NetSkoumalJoogarSharedJoogarObjectAbstractFactory JavaJoogarObjectAbstractFactory

#endif // _JoogarObjectAbstractFactory_H_
