//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/dsl/NotNull.java
//

#ifndef _NotNull_H_
#define _NotNull_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaNotNull < JavaLangAnnotationAnnotation >

@end

@interface JavaNotNull : NSObject < JavaNotNull >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNotNull)

J2OBJC_TYPE_LITERAL_HEADER(JavaNotNull)

#define NetSkoumalJoogarSharedDslNotNull JavaNotNull

#endif // _NotNull_H_
