//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/util/QueryBuilder.java
//

#ifndef _QueryBuilder_H_
#define _QueryBuilder_H_

#include "J2ObjC_header.h"

@class IOSClass;
@class IOSObjectArray;
@class JavaLangStringBuilder;

@interface JavaQueryBuilder : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)appendColumnsWithJavaLangStringBuilder:(JavaLangStringBuilder *)s
                             withNSStringArray:(IOSObjectArray *)columns;

+ (NSString *)buildQueryStringWithBoolean:(jboolean)distinct
                             withNSString:(NSString *)tables
                             withNSString:(NSString *)join
                        withNSStringArray:(IOSObjectArray *)columns
                             withNSString:(NSString *)where
                             withNSString:(NSString *)groupBy
                             withNSString:(NSString *)having
                             withNSString:(NSString *)orderBy
                             withNSString:(NSString *)limit;

+ (NSString *)generatePlaceholdersWithInt:(jint)numberOfArgs;

+ (NSString *)getColumnTypeWithIOSClass:(IOSClass *)type;

@end

J2OBJC_STATIC_INIT(JavaQueryBuilder)

FOUNDATION_EXPORT NSString *JavaQueryBuilder_getColumnTypeWithIOSClass_(IOSClass *type);

FOUNDATION_EXPORT NSString *JavaQueryBuilder_generatePlaceholdersWithInt_(jint numberOfArgs);

FOUNDATION_EXPORT NSString *JavaQueryBuilder_buildQueryStringWithBoolean_withNSString_withNSString_withNSStringArray_withNSString_withNSString_withNSString_withNSString_withNSString_(jboolean distinct, NSString *tables, NSString *join, IOSObjectArray *columns, NSString *where, NSString *groupBy, NSString *having, NSString *orderBy, NSString *limit);

FOUNDATION_EXPORT void JavaQueryBuilder_appendColumnsWithJavaLangStringBuilder_withNSStringArray_(JavaLangStringBuilder *s, IOSObjectArray *columns);

FOUNDATION_EXPORT void JavaQueryBuilder_init(JavaQueryBuilder *self);

FOUNDATION_EXPORT JavaQueryBuilder *new_JavaQueryBuilder_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaQueryBuilder)

@compatibility_alias NetSkoumalJoogarSharedUtilQueryBuilder JavaQueryBuilder;

#endif // _QueryBuilder_H_
