//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/util/ReflectionUtils.java
//

#ifndef _ReflectionUtils_H_
#define _ReflectionUtils_H_

#include "J2ObjC_header.h"

@class IOSClass;
@class JavaLangReflectField;
@protocol JavaJoogarDatabaseResult;
@protocol JavaUtilList;

@interface JavaReflectionUtils : NSObject

#pragma mark Public

- (instancetype)init;

- (JavaLangReflectField *)getDeepFieldWithNSString:(NSString *)fieldName
                                      withIOSClass:(IOSClass *)type;

- (id)getFieldValueWithJavaLangReflectField:(JavaLangReflectField *)column
                                     withId:(id)object;

- (id)getFieldValueNativeWithId:(id)gObject
       withJavaLangReflectField:(JavaLangReflectField *)gField;

- (id<JavaUtilList>)getTableFieldsWithIOSClass:(IOSClass *)table;

- (jint)inflateWithJavaJoogarDatabaseResult:(id<JavaJoogarDatabaseResult>)cursor
                                     withId:(id)object
                                    withInt:(jint)startIndex;

- (void)setFieldValueFromResultWithJavaJoogarDatabaseResult:(id<JavaJoogarDatabaseResult>)result
                                   withJavaLangReflectField:(JavaLangReflectField *)field
                                                     withId:(id)object
                                                    withInt:(jint)columnIndex;

- (void)setFieldValueNativeWithId:(id)gObject
         withJavaLangReflectField:(JavaLangReflectField *)gField
                           withId:(id)gValue;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaReflectionUtils)

FOUNDATION_EXPORT void JavaReflectionUtils_init(JavaReflectionUtils *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaReflectionUtils)

@compatibility_alias NetSkoumalJoogarSharedUtilReflectionUtils JavaReflectionUtils;

#endif // _ReflectionUtils_H_
