//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/util/SchemaGenerator.java
//

#ifndef _SchemaGenerator_H_
#define _SchemaGenerator_H_

#include "J2ObjC_header.h"

@class JavaJoogarDatabase;
@protocol JavaUtilList;

@interface JavaSchemaGenerator : NSObject

#pragma mark Public

- (instancetype)initWithJavaJoogarDatabase:(JavaJoogarDatabase *)gDatabase
                              withNSString:(NSString *)gDbName;

- (void)createDatabaseWithJavaUtilList:(id<JavaUtilList>)gDomainClasses
                               withInt:(jint)gVersion;

- (void)doUpgradeWithInt:(jint)gOldVersion
                 withInt:(jint)gNewVersion
        withJavaUtilList:(id<JavaUtilList>)gDomainClasses;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSchemaGenerator)

FOUNDATION_EXPORT void JavaSchemaGenerator_initWithJavaJoogarDatabase_withNSString_(JavaSchemaGenerator *self, JavaJoogarDatabase *gDatabase, NSString *gDbName);

FOUNDATION_EXPORT JavaSchemaGenerator *new_JavaSchemaGenerator_initWithJavaJoogarDatabase_withNSString_(JavaJoogarDatabase *gDatabase, NSString *gDbName) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSchemaGenerator)

@compatibility_alias NetSkoumalJoogarSharedUtilSchemaGenerator JavaSchemaGenerator;

@interface JavaSchemaGenerator_TableColumn : NSObject {
 @public
  NSString *name_;
  NSString *type_;
  jboolean notnull_;
  NSString *dflt_value_;
  jboolean pk_;
}

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSchemaGenerator_TableColumn)

J2OBJC_FIELD_SETTER(JavaSchemaGenerator_TableColumn, name_, NSString *)
J2OBJC_FIELD_SETTER(JavaSchemaGenerator_TableColumn, type_, NSString *)
J2OBJC_FIELD_SETTER(JavaSchemaGenerator_TableColumn, dflt_value_, NSString *)

FOUNDATION_EXPORT void JavaSchemaGenerator_TableColumn_init(JavaSchemaGenerator_TableColumn *self);

FOUNDATION_EXPORT JavaSchemaGenerator_TableColumn *new_JavaSchemaGenerator_TableColumn_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaSchemaGenerator_TableColumn)

#endif // _SchemaGenerator_H_
