//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/SystemUtils.java
//

#include "J2ObjC_source.h"
#include "SystemUtils.h"
#include "java/io/InputStream.h"
#include "java/util/List.h"

@interface JavaSystemUtils : NSObject

@end

@implementation JavaSystemUtils

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getUpgradeScriptsWithNSString:", "getUpgradeScripts", "Ljava.util.List;", 0x401, NULL, NULL },
    { "openUpgradeScriptWithNSString:", "openUpgradeScript", "Ljava.io.InputStream;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _JavaSystemUtils = { 2, "SystemUtils", "net.skoumal.joogar.shared", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaSystemUtils;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaSystemUtils)
