//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/SystemUtils.java
//

#ifndef _SystemUtils_H_
#define _SystemUtils_H_

#include "J2ObjC_header.h"

@class JavaIoInputStream;
@protocol JavaUtilList;

@protocol JavaSystemUtils < NSObject, JavaObject >

- (id<JavaUtilList>)getUpgradeScriptsWithNSString:(NSString *)gDbName;

- (JavaIoInputStream *)openUpgradeScriptWithNSString:(NSString *)gScriptName;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSystemUtils)

J2OBJC_TYPE_LITERAL_HEADER(JavaSystemUtils)

#define NetSkoumalJoogarSharedSystemUtils JavaSystemUtils

#endif // _SystemUtils_H_
