//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/dsl/Table.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Table.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"

@implementation JavaTable

@synthesize name = name_;

- (instancetype)initWithName:(NSString *)name__ {
  if ((self = [super init])) {
    self->name_ = RETAIN_(name__);
  }
  return self;
}

+ (NSString *)nameDefault {
  return @"";
}

- (IOSClass *)annotationType {
  return JavaTable_class_();
}

- (NSString *)description {
  return @"@net.skoumal.joogar.shared.dsl.Table()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "name", "name", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "nameDefault", "name", "Ljava.lang.String;", 0x100a, NULL, NULL },
  };
  static const J2ObjcClassInfo _JavaTable = { 2, "Table", "net.skoumal.joogar.shared.dsl", NULL, 0x2609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaTable;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaTable)
