//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/dsl/Unique.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Unique.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"

@implementation JavaUnique

- (IOSClass *)annotationType {
  return JavaUnique_class_();
}

- (NSString *)description {
  return @"@net.skoumal.joogar.shared.dsl.Unique()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _JavaUnique = { 2, "Unique", "net.skoumal.joogar.shared.dsl", NULL, 0x2609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_JavaUnique;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaUnique)
