//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../joogar/src/main/java/net/skoumal/joogar/shared/dsl/Unique.java
//

#ifndef _Unique_H_
#define _Unique_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaUnique < JavaLangAnnotationAnnotation >

@end

@interface JavaUnique : NSObject < JavaUnique >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUnique)

J2OBJC_TYPE_LITERAL_HEADER(JavaUnique)

#define NetSkoumalJoogarSharedDslUnique JavaUnique

#endif // _Unique_H_
